
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_for_javacode_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  main:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/test_for_javacode_db
    ports:
      - "8000:8000"
    depends_on:
      - db